In [9]:
from sklearn.cluster import KMeans
import pandas as pd
import matplotlib.pyplot as plt
data=pd.read_csv('mtcars.csv')
x=data.iloc[:,1:8]
kmeans = KMeans(n_clusters=2).fit(x)
centroids = kmeans.cluster_centers_
print(centroids)
data['cluster']=kmeans.predict(x)
data

[[ 23.97222222   4.77777778 135.53888889  98.05555556   3.88222222
    2.60905556  18.68611111]
 [ 15.1          8.         353.1        209.21428571   3.22928571
    3.99921429  16.77214286]]

,cars,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb,Date,origin,type,cluster
0,Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4,01-05-2017,japan,sports,0
1,Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4,02-05-2017,japan,sports,0
2,Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1,03-05-2017,japan,compact,0
3,Hornet_4_Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1,04-05-2017,us,muscle,0
4,Hornet_Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2,05-05-2017,us,wagon,1
5,Valiant,18.1,6,225.0,105,2.76,3.460,20.22,1,0,3,1,06-05-2017,Australia,sedan,0
6,Duster_360,14.3,8,360.0,245,3.21,3.570,15.84,0,0,3,4,07-05-2017,South Africa,suv,1
7,Merc_240D,24.4,4,146.7,62,3.69,3.190,20.00,1,0,4,2,08-05-2017,Germany,sedan,0
8,Merc_230,22.8,4,140.8,95,3.92,3.150,22.90,1,0,4,2,09-05-2017,Germany,coupe,0
9,Merc_280,19.2,6,167.6,123,3.92,3.440,18.30,1,0,4,4,10-05-2017,Germany,coupe,0
10,Merc_280C,17.8,6,167.6,123,3.92,3.440,18.90,1,0,4,4,11-05-2017,Germany,coupe,0
11,Merc_450SE,16.4,8,275.8,180,3.07,4.070,17.40,0,0,3,3,12-05-2017,Germany,luxury,1
12,Merc_450SL,17.3,8,275.8,180,3.07,3.730,17.60,0,0,3,3,13-05-2017,Germany,luxury,1
13,Merc_450SLC,15.2,8,275.8,180,3.07,3.780,18.00,0,0,3,3,14-05-2017,Germany,luxury,1
14,Cadillac_Fleetwood,10.4,8,472.0,205,2.93,5.250,17.98,0,0,3,4,15-05-2017,us,luxury,1
15,Lincoln_Continental,10.4,8,460.0,215,3.00,5.424,17.82,0,0,3,4,16-05-2017,us,luxury,1
16,Chrysler_Imperial,14.7,8,440.0,230,3.23,5.345,17.42,0,0,3,4,17-05-2017,us,luxury,1
17,Fiat_128,32.4,4,78.7,66,4.08,2.200,19.47,1,1,4,1,18-05-2017,italy,family,0
18,Honda_Civic,30.4,4,75.7,52,4.93,1.615,18.52,1,1,4,2,19-05-2017,japan,compact,0
19,Toyota_Corolla,33.9,4,71.1,65,4.22,1.835,19.90,1,1,4,1,20-05-2017,japan,compact,0
20,Toyota_Corona,21.5,4,120.1,97,3.70,2.465,20.01,1,0,3,1,21-05-2017,japan,compact,0
21,Dodge Challenger,15.5,8,318.0,150,2.76,3.520,16.87,0,0,3,2,22-05-2017,us,muscle,1
22,AMC Javelin,15.2,8,304.0,150,3.15,3.435,17.30,0,0,3,2,23-05-2017,us,muscle,1
23,Camaro Z28,13.3,8,350.0,245,3.73,3.840,15.41,0,0,3,4,24-05-2017,us,muscle,1
24,Pontiac Firebird,19.2,8,400.0,175,3.08,3.845,17.05,0,0,3,2,25-05-2017,us,muscle,1
25,Fiat X1-9,27.3,4,79.0,66,4.08,1.935,18.90,1,1,4,1,26-05-2017,italy,sports,0
26,Porsche 914-2,26.0,4,120.3,91,4.43,2.140,16.70,0,1,5,2,27-05-2017,Germany,sports,0
27,Lotus Europa,30.4,4,95.1,113,3.77,1.513,16.90,1,1,5,2,28-05-2017,malaysia,sports,0
28,Ford Pantera L,15.8,8,351.0,264,4.22,3.170,14.50,0,1,5,4,29-05-2017,us,sports,1
29,Ferrari Dino,19.7,6,145.0,175,3.62,2.770,15.50,0,1,5,6,30-05-2017,italy,sports,0
30,Maserati Bora,15.0,8,301.0,335,3.54,3.570,14.60,0,1,5,8,31-05-2017,italy,sports,1
31,Volvo 142E,21.4,4,121.0,109,4.11,2.780,18.60,1,1,4,2,01-06-2017,Germany,compact,0

In [17]:
cluster1=data[data['cluster']==0]
cluster1['cars']

0          Mazda RX4
1      Mazda RX4 Wag
2         Datsun 710
3     Hornet_4_Drive
5            Valiant
7          Merc_240D
8           Merc_230
9           Merc_280
10         Merc_280C
17          Fiat_128
18       Honda_Civic
19    Toyota_Corolla
20     Toyota_Corona
25         Fiat X1-9
26     Porsche 914-2
27      Lotus Europa
29      Ferrari Dino
31        Volvo 142E
Name: cars, dtype: object

In [18]:
cluster2=data[data['cluster']==1]
cluster2['cars']

4       Hornet_Sportabout
6              Duster_360
11             Merc_450SE
12             Merc_450SL
13            Merc_450SLC
14     Cadillac_Fleetwood
15    Lincoln_Continental
16      Chrysler_Imperial
21       Dodge Challenger
22            AMC Javelin
23             Camaro Z28
24       Pontiac Firebird
28         Ford Pantera L
30          Maserati Bora
Name: cars, dtype: object